from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
WSL_HELPER_PATH = (
    ROOT
    / "integrations"
    / "openclaw"
    / "skills"
    / "larksync_feishu_local_cache"
    / "scripts"
    / "larksync_wsl_helper.py"
)

spec = importlib.util.spec_from_file_location("larksync_wsl_helper", WSL_HELPER_PATH)
if spec is None or spec.loader is None:
    raise RuntimeError(f"无法加载脚本模块: {WSL_HELPER_PATH}")
wsl_helper = importlib.util.module_from_spec(spec)
sys.modules["larksync_wsl_helper"] = wsl_helper
spec.loader.exec_module(wsl_helper)


def test_parse_default_gateway() -> None:
    sample = "default via 172.27.80.1 dev eth0 proto dhcp src 172.27.90.2 metric 100\n"
    assert wsl_helper.parse_default_gateway(sample) == "172.27.80.1"


def test_parse_resolv_nameservers() -> None:
    sample = """
# generated by WSL
nameserver 172.27.80.1
nameserver 8.8.8.8
"""
    assert wsl_helper.parse_resolv_nameservers(sample) == ["172.27.80.1", "8.8.8.8"]


def test_ensure_remote_allow_flag_adds_option() -> None:
    args = ["--base-url", "http://172.27.80.1:8000", "check"]
    patched = wsl_helper.ensure_remote_allow_flag(args)
    assert "--allow-remote-base-url" in patched
    assert patched.index("--allow-remote-base-url") < patched.index("check")


def test_ensure_remote_allow_flag_keeps_loopback() -> None:
    args = ["--base-url", "http://localhost:8000", "check"]
    patched = wsl_helper.ensure_remote_allow_flag(args)
    assert patched == args


def test_ensure_remote_allow_flag_no_duplicate() -> None:
    args = [
        "--allow-remote-base-url",
        "--base-url",
        "http://172.27.80.1:8000",
        "check",
    ]
    patched = wsl_helper.ensure_remote_allow_flag(args)
    assert patched.count("--allow-remote-base-url") == 1


def test_select_reachable_base_url() -> None:
    results = [
        wsl_helper.ProbeResult(
            name="localhost",
            base_url="http://localhost:8000",
            connect_ok=False,
            health_ok=False,
            health_status=None,
            latency_ms=10,
            error="ConnectionRefusedError",
        ),
        wsl_helper.ProbeResult(
            name="gateway",
            base_url="http://172.27.80.1:8000",
            connect_ok=True,
            health_ok=True,
            health_status=200,
            latency_ms=20,
            error=None,
        ),
    ]
    assert (
        wsl_helper.select_reachable_base_url(results) == "http://172.27.80.1:8000"
    )


def test_parse_runtime_options_defaults() -> None:
    args, options = wsl_helper.parse_runtime_options(["check"])
    assert args == ["check"]
    assert options.auto_start_local_backend is True
    assert options.auto_install_backend_deps is True


def test_parse_runtime_options_flags() -> None:
    args, options = wsl_helper.parse_runtime_options(
        [
            "--no-auto-start-local-backend",
            "--no-auto-install-backend-deps",
            "check",
        ]
    )
    assert args == ["check"]
    assert options.auto_start_local_backend is False
    assert options.auto_install_backend_deps is False


def test_build_local_backend_env_defaults(monkeypatch, tmp_path) -> None:
    monkeypatch.delenv("LARKSYNC_TOKEN_STORE", raising=False)
    monkeypatch.delenv("LARKSYNC_TOKEN_FILE", raising=False)
    monkeypatch.delenv("LARKSYNC_AUTH_REDIRECT_URI", raising=False)

    env = wsl_helper._build_local_backend_env(tmp_path)
    assert env["LARKSYNC_TOKEN_STORE"] == "file"
    assert env["LARKSYNC_TOKEN_FILE"].endswith("token_store_wsl.json")
    assert env["LARKSYNC_AUTH_REDIRECT_URI"] == "http://localhost:8000/auth/callback"


def test_sanitize_pythonpath_removes_mismatched_site_packages() -> None:
    raw = r"F:\File\Linux\Python312\site-packages;C:\repo\apps\backend"
    sanitized, changed = wsl_helper._sanitize_pythonpath(raw)
    assert changed is True
    assert sanitized == r"C:\repo\apps\backend"


def test_build_runtime_env_cleans_pythonpath(monkeypatch) -> None:
    monkeypatch.setenv(
        "PYTHONPATH",
        r"F:\File\Linux\Python312\site-packages;C:\repo\apps\backend",
    )
    env = wsl_helper._build_runtime_env()
    assert env.get("PYTHONPATH") == r"C:\repo\apps\backend"
