from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
WSL_HELPER_PATH = (
    ROOT
    / "integrations"
    / "openclaw"
    / "skills"
    / "larksync_feishu_local_cache"
    / "scripts"
    / "larksync_wsl_helper.py"
)

spec = importlib.util.spec_from_file_location("larksync_wsl_helper", WSL_HELPER_PATH)
if spec is None or spec.loader is None:
    raise RuntimeError(f"无法加载脚本模块: {WSL_HELPER_PATH}")
wsl_helper = importlib.util.module_from_spec(spec)
sys.modules["larksync_wsl_helper"] = wsl_helper
spec.loader.exec_module(wsl_helper)


def test_parse_default_gateway() -> None:
    sample = "default via 172.27.80.1 dev eth0 proto dhcp src 172.27.90.2 metric 100\n"
    assert wsl_helper.parse_default_gateway(sample) == "172.27.80.1"


def test_parse_proc_net_route() -> None:
    sample = """Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT
eth0\t00000000\t010050AC\t0003\t0\t0\t0\t00000000\t0\t0\t0
eth0\t000050AC\t00000000\t0001\t0\t0\t0\t00F0FFFF\t0\t0\t0
"""
    assert wsl_helper.parse_proc_net_route(sample) == "172.80.0.1"


def test_parse_resolv_nameservers() -> None:
    sample = """
# generated by WSL
nameserver 172.27.80.1
nameserver 8.8.8.8
"""
    assert wsl_helper.parse_resolv_nameservers(sample) == ["172.27.80.1", "8.8.8.8"]


def test_ensure_remote_allow_flag_adds_option() -> None:
    args = ["--base-url", "http://172.27.80.1:8000", "check"]
    patched = wsl_helper.ensure_remote_allow_flag(args)
    assert "--allow-remote-base-url" in patched
    assert patched.index("--allow-remote-base-url") < patched.index("check")


def test_ensure_remote_allow_flag_keeps_loopback() -> None:
    args = ["--base-url", "http://localhost:8000", "check"]
    patched = wsl_helper.ensure_remote_allow_flag(args)
    assert patched == args


def test_ensure_remote_allow_flag_no_duplicate() -> None:
    args = [
        "--allow-remote-base-url",
        "--base-url",
        "http://172.27.80.1:8000",
        "check",
    ]
    patched = wsl_helper.ensure_remote_allow_flag(args)
    assert patched.count("--allow-remote-base-url") == 1


def test_select_reachable_base_url() -> None:
    results = [
        wsl_helper.ProbeResult(
            name="localhost",
            base_url="http://localhost:8000",
            connect_ok=False,
            health_ok=False,
            health_status=None,
            latency_ms=10,
            error="ConnectionRefusedError",
        ),
        wsl_helper.ProbeResult(
            name="gateway",
            base_url="http://172.27.80.1:8000",
            connect_ok=True,
            health_ok=True,
            health_status=200,
            latency_ms=20,
            error=None,
        ),
    ]
    assert (
        wsl_helper.select_reachable_base_url(results) == "http://172.27.80.1:8000"
    )
